language: php
sudo: required

php:
  - 7.4
git:
  depth: false

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.22.0
      COMPOSER_MEMORY_LIMIT=-1
addons:
  apt:
    packages:
      - docker-ce

# Cache Composer, NPM & Drush directories.
cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.npm
    - $HOME/.drush/cache

# Setup the environment.
before_install:
  # Be sure no mails are going out by disabling sendmail.
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Upgrade docker compose.
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  # Update the git branch by composer and create a project.
  - |
    source scripts/util/get-branch.sh
    export GIT_BRANCH=$GIT_BRANCH
    export GIT_COMMIT=$(git rev-parse HEAD)
    ./scripts/util/replace-vars.sh < tests/drupal-project/package.envsubst.json > tests/drupal-project/package.json
    git fetch origin $GIT_BRANCH:$GIT_BRANCH
    composer create-project drunomics/drupal-project:"dev-$GIT_BRANCH#$GIT_COMMIT" --no-install --repository=tests/drupal-project/package.json project
    cd project && composer install && cd ../

script:
  - cd project && vendor/bin/phapp setup localdev
  # Fix permissions in docker container by setting the right user.
  - export COMPOSE_DEFAULT_USER=$(id -u $USER)
  - docker-compose up -d
  - echo "Waiting for mysql to come up..." && docker-compose exec cli /bin/bash -c "while ! echo exit | nc mariadb 3306; do sleep 1; done" >/dev/null
  - docker-compose exec cli phapp install --no-build
  - curl -v http://example.project.localdev.space | grep "Drupal 9"

after_success:
  - echo "SUCCESS!"
