language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

mysql:
  database: myproject
  username: root
  encoding: utf8

env:
  - TEST=PHP_CodeSniffer
  - TEST=PHPUnit
  - TEST=Behat

matrix:
  exclude:
    - php: 5.6
      env: TEST=PHP_CodeSniffer
    - php: 7.0
      env: TEST=PHP_CodeSniffer

before_install:
  # Remove Xdebug as we don't need it and it causes "PHP Fatal error: Maximum
  # function nesting level of '256' reached". We don't care if that file exists
  # or not on PHP 7.
  - phpenv config-rm xdebug.ini || true

  # Update composer.
  - composer --verbose self-update

  # Create database.
  - mysql -e 'create database myproject'

install:
  # Install Composer dependencies.
  - composer --verbose install

  # Define build properties for the local test environment.
  - echo -e "drupal.base_url = http://localhost:8888\n" > build.properties.local

  # Build the project.
  - ./vendor/bin/phing build-dev

  # Install Drupal. This is not needed when doing a coding standards check.
  - test ${TEST} == "PHP_CodeSniffer" || ./vendor/bin/phing install-dev

  # Start a web server on port 8888 in the background.
  - cd $TRAVIS_BUILD_DIR/web
  - nohup php -S localhost:8888 > /dev/null 2>&1 &

  # Wait until the web server is responding.
  - until curl -s localhost:8888; do true; done > /dev/null
  - cd $TRAVIS_BUILD_DIR

script: ./scripts/travis-ci/run-test.sh ${TEST}
