language: php
sudo: required

php:
  - 7.1

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.22.0
      COMPOSER_MEMORY_LIMIT=-1
addons:
  apt:
    packages:
      - docker-ce


# Cache Composer, NPM & Drush directories.
cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.npm
    - $HOME/.drush/cache

# Setup the environment.
before_install:
  # Be sure no mails are going out by disabling sendmail.
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Upgrade docker compose.
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  # Composer does not like shallow clones, so clone again.
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT

script:
  # Ensure the project is creatable with the latest commit.
  - export GIT_COMMIT=$(git rev-parse HEAD)
  - composer create-project drunomics/drupal-project:"4.x-dev#$GIT_COMMIT" --repository=tests/drupal-project/package.json project

after_success:
  - echo "SUCCESS!"
