version: 2
jobs:
  build:
    docker:
      - image: wunderio/circleci-builder

    steps:
      - checkout

      - run: phpcs --standard=phpcs.xml

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}

      - run: composer install -n --prefer-dist --ignore-platform-reqs

      - save_cache:
          paths:
            - ./vendor
            - ./web/core
            - ./web/modules/contrib
            - ./web/themes/contrib
            - ./web/profiles/contrib
            - ./web/libraries
          key: v1-dependencies-{{ checksum "composer.lock" }}

      - restore_cache:
          keys:
            - v1-yarn-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-yarn-{{ checksum "yarn.lock" }}

      - setup_remote_docker

      # build and push Docker image
      - run: |
          docker login -u $KONTENA_DOCKER_USER -p $KONTENA_DOCKER_PASSWORD images.kontena.io

          BRANCH_SLUG="${CIRCLE_BRANCH//\//-}"
          STACK_SLUG=${BRANCH_SLUG#'feature-'}
          STACK_SLUG=${STACK_SLUG#'bug-'}
          STACK_SLUG=${STACK_SLUG#'hotfix-'}
          STACK_SLUG=${STACK_SLUG:0:15}
          STACK_NAME="$CIRCLE_PROJECT_REPONAME-$STACK_SLUG"

          export VIRTUALHOST="${BRANCH_SLUG}.${CIRCLE_PROJECT_REPONAME}.dev.wdr.io"
          export DRUPALDOCKERIMAGE="wunder/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"
          export LOADBALANCER="loadbalancer/dev_lb"
          export BASICAUTH="wunder:wunder"

          # Build the images and push them to the repository.
          kontena stack build --name $STACK_NAME

  deploy:
    docker:
      - image: wunderio/circleci-builder

    steps:
      - checkout

      - run: |
          BRANCH_SLUG="${CIRCLE_BRANCH//\//-}"
          STACK_SLUG=${BRANCH_SLUG#'feature-'}
          STACK_SLUG=${STACK_SLUG#'bug-'}
          STACK_SLUG=${STACK_SLUG#'hotfix-'}
          STACK_SLUG=${STACK_SLUG:0:15}
          STACK_NAME="$CIRCLE_PROJECT_REPONAME-$STACK_SLUG"

          export VIRTUALHOST="${BRANCH_SLUG}.${CIRCLE_PROJECT_REPONAME}.dev.wdr.io"
          export DRUPALDOCKERIMAGE="wunder/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"
          export LOADBALANCER="loadbalancer/dev_lb"
          export BASICAUTH="wunder:wunder"

          # Create the volume for files if needed.
          kontena volume create --driver local --scope stack "${STACK_NAME}_files" || kontena volume show "${STACK_NAME}_files"

          # Create or update the stack for the current branch.
          kontena stack install --name $STACK_NAME || kontena stack upgrade $STACK_NAME

          # Run drush commands within the deployed environment.
          kontena service exec $STACK_NAME/drupal drush update-db -y --root=/var/www/html/web
          kontena service exec $STACK_NAME/drupal drush config-import -y --root=/var/www/html/web
          kontena service exec $STACK_NAME/drupal drush entity-updates -y --root=/var/www/html/web

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: dev_wdr_io
      - deploy:
          requires:
            - build
          context: dev_wdr_io
